void get_MODE();
void init_spi();
void toggle();
void toggle_CSN();
unsigned char get_STATUS();
unsigned char NRF_RW(unsigned char command,unsigned char dat);
unsigned char merge(unsigned char target,unsigned char value,unsigned char shift,unsigned char mask);
void power_mode(unsigned char down);
void RX_mode();
void TX_mode();
void set_data_rate(unsigned char rate);
void set_RF_CH(unsigned char ch);
void TX_output_power_control(unsigned char pwr);
void RX_LNA_gain(unsigned char gain);
void RX_set_static_payload(char reg,char length);
void enable_dynamic_payload(char pipe);
void set_address_width(unsigned char width);
void TX_set_address(unsigned char addr_width,unsigned char * addr);
void TX_enable_auto_ack(unsigned char pipe);
void TX_disable_auto_ack(unsigned char pipe);
void CRC_config(char crc);
void TX_auto_retransmit(unsigned char delay, unsigned char count);
void RX_ack_with_payload(unsigned char pipe,unsigned char dat_width,unsigned char * dat);
void TX_write_buffer(unsigned char dat_width,unsigned char *dat );
void set_pipe_address(unsigned char pipe,unsigned char width,unsigned char *address);